image: node:latest

stages:
  - lint
  - test
  - deploy

eslint:
  stage: lint
  script:
    - cd app
    - npm install
    - node_modules/.bin/eslint --init
    - node_modules/eslint/bin/eslint.js

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - cd app
    - npm install jest
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: app/coverage/cobertura-coverage.xml

deploy:
  stage: deploy
  environment: production
  only:
    - master
  image: google/cloud-sdk
  services:
    - docker:dind
  before_script: []
  script:
    - echo $GCP_CLOUD_BUILD_SERVICE_KEY > gcloud-service-key.json
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=cloudbuild.yaml
