image: python:3.10.8

stages:
  - linting
  - testing

before_script:
  - apt-get update
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev
  - export VENV_HOME_DIR=$(pipenv --venv)
  - source $VENV_HOME_DIR/bin/activate

imports ordering:
  stage: linting
  interruptible: true
  script:
    - isort . --check-only --profile black

style checks:
  stage: linting
  interruptible: true
  script:
    - flake8 --max-line-length=88 --extend-ignore=E203,E501 .

type checks:
  stage: linting
  interruptible: true
  script:
    - mypy food_snap/* --strict

format checks:
  stage: linting
  interruptible: true
  script:
    - black . --check

unit tests:
  stage: testing
  interruptible: true
  script:
    - pytest --junitxml=report.xml --cov=food_snap/ --cov-report term-missing tests/
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml