steps:
    # Build the container image (image name: foodsnap-frontend)
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/foodsnap-frontend', '.' ]
    # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/foodsnap-frontend']
    # Deploy to Cloud Run (service name: foodsnap-frontend)
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', 'foodsnap-frontend', '--image', 'gcr.io/$PROJECT_ID/foodsnap-frontend', '--region', 'europe-west1', '--allow-unauthenticated', '--port', '80']
options:
  logging: CLOUD_LOGGING_ONLY