version: '3.8'

services:

  food_snap:
    container_name: food_snap
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USERPOLLING=true
    